genre_list = ['Blues', 'Brass & Military', "Children's", 'Classical', 'Electronic',
              'Folk, World, & Country', 'Funk / Soul', 'Hip Hop', 'Jazz', 'Latin',
              'Non-Music', 'Pop', 'Reggae', 'Rock', 'Stage & Screen']

country_list = ['Abkhazia', 'Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola',
                 'Anguilla', 'Antarctica', 'Antigua & Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Asia', 'Australasia',
                'Australia', 'Australia & New Zealand', 'Austria', 'Austria-Hungary', 'Azerbaijan', 'Bahamas, The', 
                'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgian Congo', 'Belgium', 'Belize', 'Benelux', 'Benin',
                'Bermuda', 'Bhutan', 'Bohemia', 'Bolivia', 'Bosnia & Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands',
                'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands',
                'Central African Republic', 'Central America', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
                'Congo, Democratic Republic of the', 'Congo, Republic of the', 'Cook Islands', 'Costa Rica',
                'Croatia', 'Cuba', 'Curaçao', 'Cyprus', 'Czech Republic', 'Czech Republic & Slovakia', 'Czechoslovakia',
                'Dahomey', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Dutch East Indies', 'East Timor', 
                'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Ethiopia', 'Europe', 
                'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'France & Benelux', 'French Guiana', 
                'French Polynesia', 'Gabon', 'Gambia, The', 'Gaza Strip', 'Georgia', 'German Democratic Republic (GDR)', 
                'Germany', 'Germany & Switzerland', 'Germany, Austria, & Switzerland', 'Ghana', 'Gibraltar', 'Greece', 
                'Greenland', 'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 
                'Gulf Cooperation Council', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hong Kong & Thailand', 'Hungary', 
                'Iceland', 'India', 'Indochina', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle Of Man', 'Israel', 'Italy', 
                'Ivory Coast', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Korea (pre-1945)', 
                'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
                'Lithuania', 'Luxembourg', 'Macau', 'Macedonia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 
                'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Middle East', 
                'Moldova, Republic of', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Namibia', 
                'Nauru', 'Nepal', 'Netherlands', 'Netherlands Antilles', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 
                'Nigeria', 'Niue', 'Norfolk Island', 'North & South America', 'North America (inc Mexico)', 'North Korea', 
                'Northern Mariana Islands', 'Norway', 'Oman', 'Ottoman Empire', 'Pakistan', 'Palau', 'Palestine', 'Panama', 
                'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland', 'Portugal', 
                'Protectorate of Bohemia and Moravia', 'Puerto Rico', 'Qatar', 'Reunion', 'Rhodesia', 'Romania', 'Russia', 
                'Russia & CIS', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Pierre and Miquelon', 
                'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 
                'Scandinavia', 'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles', 'Sierra Leone', 'Singapore', 
                'Singapore & Malaysia', 'Singapore, Malaysia & Hong Kong', 'Singapore, Malaysia, Hong Kong & Thailand', 
                'Sint Maarten', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South America', 
                'South East Asia', 'South Korea', 'South Pacific', 'South Vietnam', 'South West Africa', 'Southern Rhodesia', 
                'Southern Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden', 'Switzerland', 'Syria', 
                'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga', 'Trinidad & Tobago', 'Tunisia', 'Turkey', 
                'Turkmenistan', 'Turks and Caicos Islands', 'UK', 'UK & Europe', 'UK & France', 'UK & Germany', 'UK & Ireland', 
                'UK & US', 'UK, Europe & Israel', 'UK, Europe & Japan', 'UK, Europe & US', 'US', 'USA & Canada', 'USA & Europe', 
                'USA, Canada & Europe', 'USA, Canada & UK', 'USSR', 'Uganda', 'Ukraine', 'United Arab Emirates', 'Upper Volta', 
                'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam', 'Virgin Islands', 'Wallis and Futuna', 
                'West Bank', 'Worldwide', 'Yemen', 'Yugoslavia', 'Zaire', 'Zambia', 'Zanzibar', 'Zimbabwe']